name: devsecops-pipeline
on: 
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
      - '**/README.md'
jobs:
  devsecops-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "hello world"
